version: '3.9'

services:
  api:
    container_name: Vessel.API
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: dev
    command: pnpm run start:dev api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    container_name: Vessel.MongoDB
    image: docker.io/bitnami/mongodb:7.0
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    ports:
      - '27017:27017'

volumes:
  mongodb_data:
    driver: local 