app:
  port: 3333
  name: 'Ahbaco Backend'
  secret: 'kLYrGyES3ASLDdz6hD5DeVX0gqIa2Df3'
  webDir: 'http://localhost:3000'
  domain: 'http://localhost:3333'
mongodb:
  uri: 'mongodb://mongodb/master'
  master: 'master_local_db'
  system: 'system_local_db'
rate:
  ttl: 6000
  limit: 10
jwt:
  expire: 900
  refreshExpire: 86400
stripe:
  secretKey: 'sk_test_51OOk4dAFNwU4H76Q7Q2FvniRiGk8tUh2jEEjyb4S0hIhyWBtZYKXyQjSVGUZgOjRvTAm3jBM05HKlqEi2M8WOCsP00eQ73Z0Xr'
  publicKey: 'pk_test_51OOk4dAFNwU4H76QataonAHAqoapgN2YMftVHInk58FwjjXZ6iiLXG3lvoOEE73Z0Fyla2Fvwu8oWQaTpZWHgIQh00k81cb2Fw'  
  webhookSecret: 'whsec_ac373918e1e83a4ef4e2450ddd871a4800585a2c22ae0f1c4be6507dec1195a2'
redis:
  host: 'localhost'
  port: 6363
  password: 'redispassword'
  username: 'default'
  database: 0
smtp:
  transport: 'smtps://trap:trap@localhost:8003'
  emailFrom: 'no-reply@example.com'
  senderName: 'My API'
  host: 'localhost'
  port: 8003
  user: 'user@mailhogss.com'
  password: '123456'
  secure: false
  ignoreTLS: true
rmq:
  uri: 'amqp://rmq:5672'