/**
 * @file Automatically generated by barrelsby.
 */

export * from "./api-error.decorator";
export * from "./api-paginated.decorator";
export * from "./api-return.decorator";
export * from "./authorized.decorator";
export * from "./inject-admin-service.decorator";
export * from "./inject-auth-service.decorator";
export * from "./inject-notification-service.decorator";
export * from "./match.decorator";
export * from "./role.decorator";
